# -*- coding: utf-8 -*-
"""2학기 수업

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFwjHkzMnNCZticNRabqBTNClLDLIzu_
"""

#for (int i = 0 ; i < 10 ; i++)
#range(10) = 0~9 == range(0,10) == range(0,10,1) 0~10전까지 +1step
for i in range(2,20):
  print(f'{i}단')
  #1부터 10000까지 반복 출력
  #1~10000
  for k in range(1,20):
    print(f'{i} * {k}' f' = {i*k}',end = '\n')
  print('')

#반복문

#내가 입력한 단만 출력
user_input = int(input('단을 입력해주세요 '))
for k in range(1,10) : #1부터 9까지 하나씩 가져와서 k 변수에 저장
  # 콜론(:)을 찍어서 들여쓰기 = 반복하면서 할 일을 지정
  print(f'{user_input} * {k} = {user_input*k}')

for i in range(2,5):
  for k in range(1,10):
    print(f'{i} * {k} = {i*k}')

for k in range(1,20): #1~9
  #2단 ~9단 옆으로 출력
  #엔터 한번
  for i in range(2,10):
    print(f'{i} * {k} = {i*k}',end = '\t')
  print(' ')

cols = int(input('세로줄 : ')) #세로줄
rows = int(input('가로줄 : ')) #가로즐

for i in range(0,(rows*4),4):
  for k in range(0,cols):
    print(f'{i+k}', end = '\t')
  print('')

cnt = 0
for i in range(4):
  for k in range(6):
    print(f'{cnt}', end='\t')
    cnt = cnt + 1
  print()

import random
cols = int(input('세로줄 : ')) #세로줄
rows = int(input('가로줄 : ')) #가로즐
#4 * 6 = 24명 칸 준비

#실제 학생수가 24 보다 클수도 있고, 작을 수도 있음..
#만약 24보다 크다면 어떻할래? 지금은 가정하지 않겠음..
#만약 적으면... 없는 자리를 X로 표시해서 24로 무조건 만들겠음.

student = ['고현준','곽권','김규민','김민성','김민후','김서빈','김지민','박민지','박진우','박현지','신보경','양현욱','유승찬','유호진','이서연','이서영','이의인','이태한','장성준','전민준','정인서','조은호','최웅']
#student를 무조건 24명으로 만들어 버림(없는자리는 X로 해서)
#현재 23명 있음, 어떻게 24로 만들까? 현재가 만약 n명이라면?
#현재가 몇명인지 알 수 있음?
#len(student) = 현재 인원
#student.append('X') 하면 한명 추가
student_length = len(student)
for s in range(cols*rows - student_length):
  student.append('X')
  #부족한 만큼 X를 채움

random.shuffle(student) #배열 랜덤 뽑는법
cnt = 0
for i in range(rows):
  for k in range(cols):
    print(f'{student[cnt]}', end='\t')
    cnt = cnt + 1
  print()

for i in range(3):
  for k in range(5):
    print(f'*',end='')
  print()
print('==========')
for i in range(1,5,1):
  for k in range(0,i,1):
    print(f'*',end='')
  print()

#행번호 i를 입력받아 출력하는 별을 출력하는 코드
i = int(input('행번호 입력 '))
for a in range(1,i+1,1):
  for k in range(0,a,1):
    print(f'*',end='')
  print()
print('=============')
#2번째 방법
rows = int(input('행번호 입력 '))
for b in range(rows):
  for c in range(b+1):
      print(f'*',end='')
  print()
print('=============')
#반대
rows2 = int(input('행번호 입력 '))
for a in range(rows2+1,1,-1):
  for k in range(1,a,1):
    print(f'*',end='')
  print()
#반대 2번째 방법
rows3 = int(input('행번호 입력 '))
for b in range(rows3):
  for c in range(rows3-b):
      print(f'*',end='')
  print()

i = int(input('행번호 입력 '))
for a in range(i):
  for b in range(i-a-1):#5 - 0 - 1 = 4
          print(f'_',end='')
  for b in range(a+1):
    print(f'*',end='')
  print()

#0000
#1111
#2222
#3333
#4444
for i in range(5): # 0~4
  for k in range(5):
    print(f'{i}',end="")
  print()

for i in range(4):
  for k in range(5):
    # i,k를 활용할 수 있을까?
    # 어떻하면 음수를 만들 수 있을까?
    if i % 2 == 1:
      print(f'{i*-1}',end="")
    else:
      print(f'{i}',end="")
  print()
print("================")
sw = -1
for i in range(1,6):
  for k in range(5):
      print(f'{i * sw}',end="")
  sw = sw*-1
  print()
print("================")
sw = 1
for i in range(1,6):
  for k in range(5):
      print(f'{i * sw}',end="")
  sw = sw*-1
  print()

import math

a = 2.5
print(math.ceil(a))

b= int(7.5)
print(int(b))

#n이 무조건 홀수
# 5 입력
#00*00
#0***0
#*****
#0***0
#00*00
for j in range(3):
  for i in range(3,0,-1):
    print("0",end="")
    for k in range(1,7,2):
      print("8",end="")
    print()